import React from "react";

interface JsonLdProps {
  type: "organization" | "faq" | "breadcrumb";
  faqItems?: { question: string; answer: string }[];
  breadcrumbItems?: { name: string; item: string }[];
}

export default function JsonLd({ type, faqItems, breadcrumbItems }: JsonLdProps) {
  let data: any = null;

  if (type === "organization") {
    data = {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "FinancialService",
          "@id": "https://app.xorr.finance/#organization",
          "name": "XORR Finance",
          "url": "https://app.xorr.finance",
          "logo": "https://app.xorr.finance/xorr-logo.png",
          "image": "https://app.xorr.finance/xorr-logo.png",
          "description": "Private consumer credit on Sui — BNPL, lending, and a credit score that never leaves a confidential TEE.",
          "tagline": "Buy Now, Pay Never.",
          "feesAndCommissionsSpecification": "Auto-repaid from on-chain yield generated by collateral assets.",
          "sameAs": [
            "https://x.com/XorrFinance"
          ]
        },
        {
          "@type": "WebSite",
          "@id": "https://app.xorr.finance/#website",
          "url": "https://app.xorr.finance",
          "name": "XORR Finance",
          "description": "Private consumer credit on Sui: BNPL, lend/borrow, and a TEE-computed credit score.",
          "publisher": {
            "@id": "https://app.xorr.finance/#organization"
          }
        }
      ]
    };
  } else if (type === "faq") {
    const items = faqItems || [
      {
        question: "What is Buy Now, Pay Never?",
        answer: "Buy Now, Pay Never (BNPL) allows users to purchase items on credit by locking USDC collateral. The collateral is automatically routed to yield-generating protocols (such as lending pools or liquidity pools on Sui), and the earned yield pays off the outstanding credit over time."
      },
      {
        question: "How does the TEE credit score work?",
        answer: "XORR Finance computes your credit score inside an AWS Nitro TEE (Trusted Execution Environment). It processes off-chain financial data confidentially, issuing an on-chain cryptographic attestation. Your raw financial data never leaves the enclave."
      },
      {
        question: "Is my financial data private?",
        answer: "Yes. Because all computations occur inside a confidential enclave (TEE), no one—not even the XORR protocol developers—can inspect your private financial data. Only the final score is attested on-chain."
      },
      {
        question: "What is XORR Finance built on?",
        answer: "XORR Finance is built natively on the high-performance Sui blockchain, leveraging its low latency, high throughput, and secure smart contracts to handle collateral management, lending pools, and BNPL checkouts."
      }
    ];
    data = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": items.map((item) => ({
        "@type": "Question",
        "name": item.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": item.answer
        }
      }))
    };
  } else if (type === "breadcrumb") {
    data = {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": (breadcrumbItems || []).map((item, index) => ({
        "@type": "ListItem",
        "position": index + 1,
        "name": item.name,
        "item": item.item
      }))
    };
  }

  if (!data) return null;

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
