-- Create merchants table
create table merchants (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  icon text,
  credit_limit numeric,
  plan_description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create pools table
create table pools (
  id bigint generated by default as identity primary key,
  name text not null,
  tvl numeric not null default 0,
  apr numeric not null default 0,
  utilization numeric not null default 0,
  available_liquidity numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create limits table (system wide or per user if needed, sticking to system for now as per dashboard)
create table limits (
  id bigint generated by default as identity primary key,
  current_limit numeric not null default 0,
  used numeric not null default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create transactions table
-- Supports both merchant spends and bills
create table transactions (
  id bigint generated by default as identity primary key,
  title text not null, -- Merchant name or bill title
  amount numeric not null,
  asset text not null default 'USDC',
  category text, -- 'spend', 'bill', 'repayment'
  status text not null default 'pending', -- 'pending', 'confirmed', 'verified'
  tx_hash text,
  user_id uuid references auth.users(id), -- Optional if we want global visibility for demo, but good for real app
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table merchants enable row level security;
alter table pools enable row level security;
alter table limits enable row level security;
alter table transactions enable row level security;

-- Create policies (Open for read for now for simplicity in demo, restrictive for write)
create policy "Public Read Merchants" on merchants for select using (true);
create policy "Public Read Pools" on pools for select using (true);
create policy "Public Read Limits" on limits for select using (true);
create policy "Public Read Transactions" on transactions for select using (true);
create policy "Public Insert Transactions" on transactions for insert with check (true);
create policy "Public Update Transactions" on transactions for update using (true);

-- Insert Seed Data for Merchants
insert into merchants (name, category, icon, credit_limit, plan_description) values
('GLOBAL_MARKET_ACCESS', 'Travel', 'Globe', 1200, '4_PAYMENTS // 0%_APR'),
('GAMING_HUB_INTERFACE', 'Gaming', 'Gamepad2', 850, '4_PAYMENTS // 0%_APR'),
('HARDWARE_NODE_SYNDICATE', 'Technology', 'Cpu', 2500, '4_PAYMENTS // 0%_APR'),
('LIFESTYLE_ASSET_VAULT', 'Fashion', 'Sparkles', 500, '4_PAYMENTS // 0%_APR'),
('MEDIA_STREAM_RELAY', 'Entertainment', 'Tv', 300, '4_PAYMENTS // 0%_APR'),
('ADVANCED_TECH_RESOURCES', 'Technology', 'Zap', 1800, '4_PAYMENTS // 0%_APR');

-- Insert Seed Data for Limits
insert into limits (current_limit, used) values (200, 32);

-- Insert Seed Data for Transactions
insert into transactions (title, amount, asset, category, status, created_at) values
('Whole Foods Market', 124.50, 'USDC', 'spend', 'verified', now() - interval '20 minutes'),
('Netflix Subscription', 15.99, 'USDC', 'spend', 'verified', now() - interval '1 hour'),
('Electric Bill', 45.00, 'USDC', 'bill', 'pending', now() + interval '5 days');
