-- Migration: activity_logging_v1
-- Description: Adds cross-chain tracking to transactions and ensures activity tables exist.

-- 1. Ensure deposits table exists for tracking bridge attempts
CREATE TABLE IF NOT EXISTS deposits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_hash TEXT UNIQUE NOT NULL,
    hub_tx_hash TEXT,
    user_address TEXT,
    amount NUMERIC,
    token_address TEXT,
    chain_key BIGINT DEFAULT 1, -- 1 = Sepolia
    status TEXT DEFAULT 'PENDING',
    proof JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Ensure bridge_transactions table exists for finalized bridge history
CREATE TABLE IF NOT EXISTS bridge_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_tx_hash TEXT UNIQUE NOT NULL,
    hub_tx_hash TEXT,
    user_address TEXT,
    amount NUMERIC,
    token_address TEXT,
    source_chain_id BIGINT,
    dest_chain_id BIGINT,
    status TEXT DEFAULT 'COMPLETED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Enhance main transactions table with blockchain breadcrumbs
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS hub_tx_hash TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS chain_id BIGINT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS user_address TEXT;

-- 4. Set up RLS Policies for the new tables
ALTER TABLE deposits ENABLE ROW LEVEL SECURITY;
ALTER TABLE bridge_transactions ENABLE ROW LEVEL SECURITY;

-- Allow public access for demo purposes (matching existing schema pattern)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Deposits') THEN
        CREATE POLICY "Public Read Deposits" ON deposits FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Deposits') THEN
        CREATE POLICY "Public Write Deposits" ON deposits FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Deposits') THEN
        CREATE POLICY "Public Update Deposits" ON deposits FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Bridge') THEN
        CREATE POLICY "Public Read Bridge" ON bridge_transactions FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Bridge') THEN
        CREATE POLICY "Public Write Bridge" ON bridge_transactions FOR INSERT WITH CHECK (true);
    END IF;
END $$;

-- Refresh PostgREST
NOTIFY pgrst, 'reload schema';
