-- Migration: developer_console_v1
-- Description: Adds tables for the Obolus Developer Console (Merchant Console)

-- 1. Merchant Users (Links wallet or auth provider ID to internal user)
CREATE TABLE IF NOT EXISTS merchant_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_address TEXT UNIQUE NOT NULL, -- The main identity for now (Web3 login)
    email TEXT, -- Optional contact email
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Merchant Apps (Projects created by a user)
CREATE TABLE IF NOT EXISTS merchant_apps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES merchant_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    category TEXT, -- 'E-commerce', 'Gaming', etc.
    client_id TEXT UNIQUE NOT NULL DEFAULT md5(random()::text || clock_timestamp()::text)::uuid, -- Public Identifier
    client_secret TEXT NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'), -- Private Secret (hashed? stored plain for MVP keygen)
    escrow_contract TEXT, -- Deployed contract address on Creditcoin
    network TEXT DEFAULT 'creditcoin_testnet',
    status TEXT DEFAULT 'active', -- 'active', 'suspended'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. API Keys (For backend integration, apart from client_id/secret flow if needed)
-- For MVP, client_id/secret on the App might suffice, but keys allow rotation without changing app ID.
CREATE TABLE IF NOT EXISTS api_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    app_id UUID REFERENCES merchant_apps(id) ON DELETE CASCADE,
    key_hash TEXT NOT NULL, -- Recommended to store hash, user sees key once
    label TEXT, -- 'Production Server', 'Test Runner'
    last_used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Webhooks (Event subscriptions)
CREATE TABLE IF NOT EXISTS webhooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    app_id UUID REFERENCES merchant_apps(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    secret TEXT NOT NULL, -- Used to sign payload
    events TEXT[] NOT NULL, -- ['payment.received', 'loan.requested']
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Webhook Delivery Logs (Debugging)
CREATE TABLE IF NOT EXISTS webhook_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id UUID REFERENCES webhooks(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    response_status INTEGER,
    response_body TEXT,
    attempt_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE merchant_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhooks ENABLE ROW LEVEL SECURITY;

-- For MVP/Demo, we might use simple policies or service role.
-- Assuming Supabase Auth might map to `auth.users` eventually, but for now we manage `merchant_users` manually via wallet signature.
-- "Public" access for now to unblock development, restricted by application logic.

CREATE POLICY "Enable read access for all users" ON merchant_users FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON merchant_users FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON merchant_apps FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON merchant_apps FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON merchant_apps FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON webhooks FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON webhooks FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON webhooks FOR UPDATE USING (true);

-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
